### ISSUE TITLE
Constantly getting error: 'Invalid "redirect_uri" query parameter. '

### ISSUE THREAD

**Issue by rankun203** [mach-kernel/dwolla-token-generator#6]
I have `https://tokengenerator.dwolla.com/redirect` in my application settings.

![qq20151105-2 2x](https://cloud.githubusercontent.com/assets/2988555/10964572/e60aa846-83e2-11e5-997d-20dee86b8e67.png)

As shown in the screenshot.

I get into the page: https://tokengenerator.dwolla.com/.

I'm choosing `UAT/Sandbox` way, then filled out the key and secret, then Start OAuth, but got the error above.

I noticed the URL has the `redirect_url=https://dwolla-token.herokuapp.com/redirect`, then I added it in my application's setting, then got this error:

![image](https://cloud.githubusercontent.com/assets/2988555/10967783/e698537a-83f7-11e5-966a-3282f96fe6bb.png)

I installed this tool in my server, then, still the same, after I authorised, nothing happened. This is really frustrated to me. Hope to get help from you guys.

**Comment by rankun203** [comment]
OK, I'll go with `https://dwolla-token.herokuapp.com/` first, this really takes me a lot of time. Hope you fixes this.

**Comment by mach-kernel** [comment]
We switched over to `https://tokengenerator.dwolla.com`. It's been fixed since last night, just give it another try :)
